name: Run Scraper Manually

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run scraper
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          RATE_LIMIT: 1
        run: python run_scraper.py

      - name: Upload CSV
        uses: actions/upload-artifact@v3
        with:
          name: products-csv
          path: products.csv
