name: Run Scraper

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'The first page you want to scrape'
        required:    true
        default:     'https://pricewiseinsulation.com.au/shop/material/glasswool-insulation/'
      rate_limit:
        description: 'Requests per second'
        required:    true
        default:     '1.0'

jobs:
  scrape:
    runs-on: ubuntu-latest

    # ← use github.event.inputs here, not vars
    env:
      BASE_URL:   ${{ github.event.inputs.base_url }}
      RATE_LIMIT: ${{ github.event.inputs.rate_limit }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run the scraper
        run: python run_scraper.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: products.csv
          path: products.csv
