name: Run Scraper
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ vars.BASE_URL }}
      RATE_LIMIT: ${{ vars.RATE_LIMIT }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run the scraper
        run: python run_scraper.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: products.csv
          path: products.csv
