name: Run Scraper
on:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'The product or category page URL to scrape'
        required: true
      rate_limit:
        description: 'Requests per second (e.g. 1.0)'
        required: false
        default: '1.0'

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ github.event.inputs.base_url }}
      RATE_LIMIT: ${{ github.event.inputs.rate_limit }}


    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run the scraper
        run: python run_scraper.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: variants.csv
          path: variants.csv
